---
framework: jest
modifiers:
  - type: jest
    cli: "--forbid-pending --no-bail"
postMerge:
  pattern:
    - "integration-tests/functions/__tests__/functions-dev.js"
  strategy:
    threshold: <5|100s>
    type: <commit|time>
preMerge:
  pattern:
    - "integration-tests/functions/__tests__/functions-dev.js"
stability:
  consecutive_runs: 5
preRun:
  - npm install -g gatsby-cli
postRun:
  - node --version
version: 2.0
